apps/cms/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from . import course_views
from . import staff_views

# from rest_framework import routers


app_name = 'cms'

# router = routers.DefaultRouter()
# router.register(path('',))

urlpatterns = [
    path('', views.index, name='index'),
    path('news_list/', views.NewsList.as_view(), name='news_list'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsViem.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.NewsCategoryViem.as_view(), name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners, name='banners'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),

    path('news_show', views.NewsClickShowView.as_view(), name='news_show'),
]
# 课程相关的url
urlpatterns += [
    path('pub_course/', course_views.PubCourse.as_view(), name='pub_course'),
    path('course_category/', course_views.CourseCategoryViem.as_view(), name='course_category'),
    path('add_course_category/', course_views.add_course_category, name='add_course_category'),
    path('edit_course_category/', course_views.edit_course_category, name='edit_course_category'),
    path('delete_course_category/', course_views.delete_course_category, name='delete_course_category'),
    path('course_teacher/', course_views.CourseTeacher.as_view(), name='course_teacher'),
    path('course_teacher/<pk>/', course_views.CourseTeacherDetail.as_view(), name='course_teacher_detail'),
    path('course_teacher_list/', course_views.CourseTeacherList.as_view(), name='course_teacher_list'),
    path('course_teacher_list/<pk>/', course_views.CourseTeacherListDetail.as_view(), name='course_teacher_list_detail'),
]

# 分享资料url
urlpatterns += [
    path('pay_info/', views.PayInfoIndex.as_view(), name='pay_info'),
    path('payinfo_list/', views.PayInfoList.as_view(), name='payinfo_list'),
    path('payinfo/', views.PayInfo.as_view(), name="payinfo"),
    path('payinfo/<pk>/', views.PayInfo.as_view(), name="payinfo_detail"),
]

# 用户管理相关url配置
urlpatterns += [
    path('staffs/', staff_views.staffs, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
    path('user_center/', views.UserCenter.as_view(), name='user_center'),
    path('edit_user_center/', views.EditUserCenter.as_view(), name='edit_user_center'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

apps/course/urls.py
from django.urls import path
from . import views

# 对应的应用名空间
app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='index'),
    path('detail/<course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
    path('course_order/', views.course_order, name='course_order'),
    path('notify_url/', views.notify_view, name='notify_url'),
    path('order_key/', views.order_key, name='order_key')
]

apps/news/urls.py
from django.urls import path
from . import views
# from django.shortcuts import reverse


# 设置空间名
app_name = 'news'
urlpatterns = [
	path('', views.index, name='index'),
	path('detail/<news_id>/', views.news_detail, name='news_detail'),
	path('search/', views.search, name='search'),
	path('list/', views.news_list, name='news_list'),
	path('add_comment/', views.add_comment, name='add_comment'),
]

apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order', views.payinfo_order, name='payinfo_order'),
    path('notify_view/', views.notify_view, name='notify_view'),
    path('download_payinfo/', views.download_payinfo, name='download_payinfo'),
    path('order_key/', views.order_key, name='order_key')
]

django_01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # 用来拼接一些静态文件路径
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # django自带的admin用户路由界面
    path('', include('apps.news.urls')),  # 新闻路由界面，apps.name用于区分命名空间下对应的urls
    path('account/', include('apps.xfzauth.urls')),  # 登录注册界面的主urls
    path('course/', include('apps.course.urls')),  # 创业课堂页面的主urls
    path('payinfo/', include('apps.payinfo.urls')),  # 支付界面urls
    path('cms/', include('apps.cms.urls')),  # 后台管理系统urls
    path("ueditor/", include("apps.ueditor.urls")),  # 文本编辑器urls
    # 1 将static写在urlpatterns里的写法：
    # static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)[0],
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 2 static写在外面的写法

# 说明;1.告诉当访问media文件时，可以到后面定义的settings.MEDIA_EOOT目录下寻找。这样就可以直接用浏览器通过对应的文件路径访问文件。如果不做这个配置，浏览器是不能直接根据路径访问文件的
# 2.因为urlpatterns是一个列表参数，static()返回值也是一个列表，使用“+”直接变成列表相加，最终的static()也是urlpatterns中的一个元素。等效于：urlpatterns
# += static()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/",include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link REL="SHORTCUT ICON" HREF="{% static "images/favicon.ico" %}"/>
    <link rel="stylesheet" href="{% static 'css/news/news.css' %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_710680_dzxmyw7pz3.css">
    <link rel="stylesheet" href="{% static 'css/base/front_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/base/side.css' %}">
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    {# front_base.js文件是基于jquery写的所以需要将其放在jQuery后面 #}
    <script src="{% static 'js/template-web.js' %}"></script>
    <script src="{% static 'js/front_base.js' %}"></script>
    {# xfzajax文件是基于jquery写的所以需要将其放在jQuery后面 #}
    <script src="{% static 'js/xfzajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    {% block head %}{% endblock %}
{# 只要会修改，就添加block 便于模板继承后的修改 #}
</head>
<body>
    <header class="header">
        <nav class="nav">
            <a href="{% url 'news:index' %}"><h1 class="login-box"></h1></a>

            <ul class="menu">
                <li><a href="/">首页</a></li>
                <li><a href="{% url 'course:index' %}">课程资讯</a></li>
                <li><a href="{% url 'payinfo:index' %}">知识分享</a></li>
                <li><a href="{% url 'news:search' %}">搜索</a></li>
            </ul>
            <div class="auth-group">
                <span class="user-icon icon-user iconfont"></span>
                {% if user.is_authenticated %}
                    <a href="javascript:void (0);">{{ user.username }}</a>
{#                使用"javascript:void (0);"的方式这样就是直接点击a标签不做任何操作#}
                    <div class="user-box">
                        <span>{{ front_user.username }}</span>
                    </div>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                            <a href="{% url 'cms:index' %}">管理系统</a>
                        {% endif %}

                        <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <a href="{% url 'xfzauth:login' %}">登录 /</a>
                    <a href="{% url 'xfzauth:register' %}">注册</a>
                {% endif %}
            </div>
        </nav>
    </header>

    {% block main %}{% endblock %}

    <div class="footer">
        <div class="footer-1" style="height: 85px;">
            <div class="footer-inner">
                <div class="login-box"></div>
                <div class="detail-info-group" >
                    <div class="top-group">
                        <ul class="links">
                            <li><a href="#">学习网站</a></li>
                            <li><a href="https://github.com/yuyexiaohan" target="_blank">GitHub</a></li>
                            <li><a href="https://www.liaoxuefeng.com/">廖雪峰</a></li>
                            <li><a href="https://www.djangoproject.com/">django官网</a></li>
                        </ul>
                        <div class="about-us">
                            <span>联系方式:</span>
                            <span class="weixin">achjiang</span>
{#                            <span class="weibo">创业课堂</span>#}
                        </div>
                    </div>
                    <div class="bottom-group">
                        <p class="address" style="float: left; padding-left: 80px">互联网ICP备案：：鄂ICP备18024782号</p>
{#                        <p class="contact">客服电话： xxxxxx</p>#}
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-2" style="height: 50px;">
            @2020 achjiang blog Power by Django
        </div>
    </div>
</body>
</html>

templates/base/side.html
<div class="course-group">
    <div class="top-group">
        <span class="title-group">关于</span>
        <a href="#" class="more-group">更多</a>
    </div>
</div>
<div class="pay-info-group">
    <a href="#">
        <img src="http://achjiang.cn/logo-5.png" alt="">
        <h4>一个进阶的码农...<br>生命不息 学习不止</h4>
    </a>

</div>
<div class="focus-group">
    <div class="title-group">关注</div>
    <div class="website-group">
        <div class="left-group">
            <div class="item-group">
                <div class="logo-group zhihu-logo"></div>
                <div class="text-group">
                    <a href="#">江寒</a>
                </div>
            </div>
            <div class="item-group">
                <div class="logo-group weibo-logo"></div>
                <div class="text-group">
                    <a href="#">achjiang</a>
                </div>
            </div>
        </div>
        <div class="right-group">
            <div class="qr-group"></div>
            <p class="text-group">扫码添加微信achjiang</p>
        </div>
    </div>
</div>