apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order', views.payinfo_order, name='payinfo_order'),
    path('notify_view/', views.notify_view, name='notify_view'),
    path('download_payinfo/', views.download_payinfo, name='download_payinfo'),
    path('order_key/', views.order_key, name='order_key')
]

django_01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # 用来拼接一些静态文件路径
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # django自带的admin用户路由界面
    path('', include('apps.news.urls')),  # 新闻路由界面，apps.name用于区分命名空间下对应的urls
    path('account/', include('apps.xfzauth.urls')),  # 登录注册界面的主urls
    path('course/', include('apps.course.urls')),  # 创业课堂页面的主urls
    path('payinfo/', include('apps.payinfo.urls')),  # 支付界面urls
    path('cms/', include('apps.cms.urls')),  # 后台管理系统urls
    path("ueditor/", include("apps.ueditor.urls")),  # 文本编辑器urls
    # 1 将static写在urlpatterns里的写法：
    # static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)[0],
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 2 static写在外面的写法

# 说明;1.告诉当访问media文件时，可以到后面定义的settings.MEDIA_EOOT目录下寻找。这样就可以直接用浏览器通过对应的文件路径访问文件。如果不做这个配置，浏览器是不能直接根据路径访问文件的
# 2.因为urlpatterns是一个列表参数，static()返回值也是一个列表，使用“+”直接变成列表相加，最终的static()也是urlpatterns中的一个元素。等效于：urlpatterns
# += static()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/",include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

apps/payinfo/models.py
from django.db import models
from shortuuidfield import ShortUUIDField  # 导入


class Payinfo(models.Model):
    price = models.FloatField()
    # 链接
    path = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    profile = models.CharField(max_length=100)


class PayinfoOrder(models.Model):
    uid = ShortUUIDField(primary_key=True)  # 不是自增长id
    payinfo = models.ForeignKey('Payinfo', on_delete=models.DO_NOTHING)
    amount = models.FloatField()
    # DO_NOTHING：在django中，不会做任何的处理。完全看数据库的关系
    buyer = models.ForeignKey('xfzauth.User', on_delete=models.DO_NOTHING)
    # 设置为默认值时，就会从定义的函数中取值
    # buyer = models.ForeignKey('xfzauth.User',on_delete=models.SET_DEFAULT,default=get_user())

    pub_time = models.DateTimeField(auto_now_add=True)
    # 1:代表的时支付宝支付，2：代表的时微信支付
    istype = models.SmallIntegerField(default=0)
    # 1:代表的时未支付。2：代表的时已支付
    status = models.SmallIntegerField(default=1, null=True)

apps/payinfo/views.py
import os
from hashlib import md5  # 导入md5加密

from django.shortcuts import render
from django.shortcuts import redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import FileResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required

from .models import Payinfo, PayinfoOrder
from utils import restful


def index(request):
    """付费资讯"""
    payinfos = Payinfo.objects.all()
    context = {
        'payinfos': payinfos
    }
    return render(request, 'payinfo/payinfo.html', context=context)


@login_required(login_url='/account/login/')
def payinfo_order(request):
    """付费资讯的支付"""
    payinfo_id = request.GET.get('payinfo_id')
    payinfo = Payinfo.objects.get(pk=payinfo_id)
    price = payinfo.price
    if price == 0:
        return redirect(
            reverse("payinfo:download_payinfo") +
            "?payinfo_id=%s" %
            payinfo.pk)
    else:
        buyed = PayinfoOrder.objects.filter(
            buyer=request.user, payinfo=payinfo, status=2)
        if buyed:
            return redirect(
                reverse("payinfo:download_payinfo") +
                "?payinfo_id=%s" %
                payinfo.pk)

    order = PayinfoOrder.objects.create(
        buyer=request.user,
        amount=payinfo.price,
        payinfo=payinfo,
        status=1)

    context = {
        'payinfo': payinfo,
        'order': order,
        # /payinfo/notify_url/
        'notify_url': request.build_absolute_uri(reverse('payinfo:notify_view')),
        'return_url': request.build_absolute_uri(reverse('payinfo:download_payinfo') + "?payinfo_id=%s" % payinfo.pk)
    }
    return render(request, 'payinfo/create_order.html', context=context)


def order_key(request):
    """支付加密"""
    goodsname = request.POST.get('goodsname')
    istype = request.POST.get('istype')
    notify_url = request.POST.get('notify_url')
    orderid = request.POST.get('orderid')
    price = request.POST.get('price')
    return_url = request.POST.get('return_url')

    token = 'e6110f92abcb11040ba153967847b7a6'
    uid = '49dc532695baa99e16e01bc0'
    orderuid = str(request.user.pk)

    print('goodsname:', goodsname)
    print('istype:', istype)
    print('notify_url:', notify_url)
    print('orderid:', orderid)
    print('price:', price)
    print('return_url:', return_url)
    print('token:', token)
    print('orderuid:', orderuid)

    key = md5(
        (goodsname +
         istype +
         notify_url +
         orderid +
         orderuid +
         price +
         return_url +
         token +
         uid).encode("utf-8")).hexdigest()
    # key = md5 ("".join ([goodsname, istype, notify_url, orderuid, orderuid, price, return_url, token, uid])
    # .encode ("utf-8")).hexdigest ()
    return restful.result(data={'key': key})


@csrf_exempt
def notify_view(request):
    """支付链接视图函数"""
    orderid = request.POST.get('orderid')
    PayinfoOrder.objects.filter(pk=orderid).update(status=2)
    return restful.ok()


def download_payinfo(request):
    """下载文件视图函数"""
    # 如果用户没有购买这个付费信息时，那么不能够让他下载
    payinfo_id = request.GET.get('payinfo_id')
    payinfo = Payinfo.objects.get(pk=payinfo_id)
    price = payinfo.price
    if price != 0:
        buyed = PayinfoOrder.objects.filter(
            payinfo=payinfo, buyer=request.user, status=2)
        if not buyed:
            return redirect(reverse('payinfo:index'))
    path = payinfo.path
    # 作为一个附件的形式下载，而不是作为一个普通的文件下载
    response = FileResponse(
        open(
            os.path.join(
                settings.MEDIA_ROOT,
                path),
            'rb'))
    # HTTP Content-Type标头中包含的值，包括MIME类型规范和字符集编码。
    # 如果 content_type指定，则使用其值。
    response['Content-Type'] = 'image/jpeg'
    # 'Content-Disposition'告诉浏览器将响应视为文件附件
    # >>> response = HttpResponse(my_data, content_type='application/vnd.ms-excel')
    # >>> response['Content-Disposition'] = 'attachment; filename="foo.xls"'
    # path=/20180725/xx.jpg = ['',20180725,xx.jpg]
    response['Content-Disposition'] = 'attachment;filename="%s"' % path.split(
        "/")[-1]
    return response

templates/payinfo/create_order.html
{% extends 'base/front_base.html' %}

{% block title %}
确认订单
{% endblock %}

{% block head %}
    <style>
        .table{
            width: 100%;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            background: #eaeaea;
            text-align: center;
        }
        .table{
            border-spacing: 20px;
        }
        .table img{
            width: 120px;
            height: 68px;
            float: left;
        }
        .table .title{
            margin-left: 10px;
        }
        .pay-way label{
            float: right;
        }
        .pay-way span{
            border: 1px solid #ccc;
            position: relative;
            top: 20px;
        }
        .pay-way .zfb-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            cursor: pointer;
            background: url("http://study.163.com/res/images/pay/payList.png");
            background-position: -140px 0;
            background-size: 300% 200%;
            margin-right:20px;
        }
        .pay-way .wx-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            position: relative;
            cursor: pointer;
        }
        .pay-way .wx-btn img{
            top: 12px;
            left: 16px;
            position: absolute;
        }
        .submit-group{
            overflow: hidden;
            padding: 60px 0;
            margin-bottom: 100px;
        }
        .submit-btn{
            display: block;
            text-align: center;
            width: 136px;
            height:49px;
            line-height: 49px;
            background: url("http://s.stu.126.net/res/images/pay/payBtns.png?c9b6b849b38cca45b160a96802575ac8") no-repeat 4449px 4449px;
            background-position: 0 -302px;
            border: none;
            cursor: pointer;
            color: #fff;
            font-size: 16px;
            float: right;
        }
        .submit-btn:hover{
            background-position: -139px -302px;
        }
    </style>
    <script>
    $(function () {
        $("#submit-btn").click(function (event) {
            // 需要手动执行post请求函数，所以这里阻止默认行为
            event.preventDefault();
                var goodsname = $("input[name='goodsname']").val();
                // 加入checked条件判断提取的时支付宝还是微信
                var istype = $("input[name='istype']:checked").val();
                var notify_url = $("input[name='notify_url']").val();
                var orderid = $("input[name='orderid']").val();
                var price = $("input[name='price']").val();
                var return_url = $("input[name='return_url']").val();
                xfzajax.post({
                    'url': '/payinfo/order_key/',
                    'data': {
                        'goodsname': goodsname,
                        'istype': istype,
                        'notify_url': notify_url,
                        'orderid': orderid,
                        'price': price,
                        'return_url': return_url
                    },
                    'success': function (result) {
                        if(result['code'] === 200){
                            var key = result['data']['key'];
                            var keyInput = $("input[name='key']");
                            keyInput.val(key); // 赋值给key
                            $("#order-form").submit(); //针对表单的提交事件
                        }
                    }
                });
        });
    });
    </script>
{% endblock %}



{% block main %}
    <div class="main">
        <div class="wrapper">
            <table class="table">
            <thead>
                <tr>
                    <th>商品名称</th>
                    <th>单价(元)</th>
                    <th>小计（元）</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="left">
                        <a href="#">
                            <img class="thumbnail" src="https://goss.veer.com/creative/vcg/veer/612/veer-159376678.jpg" alt="">
                            <span class="title">{{ payinfo.title }}</span>
                        </a>
                    </td>
                    <td>{{ payinfo.price }}</td>
                    <td>{{ payinfo.price }}</td>
                </tr>
            </tbody>
        </table>
            <form action="https://pay.bbbapi.com/" method="post" id="order-form">
                <input type="hidden" name="uid" value="49dc532695baa99e16e01bc0">
                <input type="hidden" name="price" value="{{ payinfo.price }}">
                <input type="hidden" name="notify_url" value="{{ notify_url }}">
                <input type="hidden" name="return_url" value="{{ return_url }}">
                <input type="hidden" name="orderid" value="{{ order.pk }}">
                <input type="hidden" name="orderuid" value="{{ order.buyer_id }}">
                <input type="hidden" name="goodsname" value="{{ payinfo.title }}">
                <input type="hidden" name="key" value="">
            <div class="pay-way">
                <label for="istype-wx">
                    <input id="istype-wx" type="radio" name="istype" value="2">
                    <span class="wx-btn">
                        <img src="http://nos.netease.com/test-edu-image/1BD9F69D6760CE1508D2269864AA54F8.png" alt="">
                    </span>
                </label>
                <label for="istype-zfb">
                    <input id="istype-zfb" type="radio" name="istype" value="1" checked>
                    <span class="zfb-btn"></span>
                </label>
                <div style="clear: both;"></div>
            </div>
            <div class="submit-group">
                <input type="submit" value="去支付" id="submit-btn" class="submit-btn">
            </div>
        </form>
        </div>
    </div>
{% endblock %}

templates/payinfo/payinfo.html
{% extends 'base/front_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/payinfo/payinfo.css" %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="main-container">
            <div class="banner">
                <img src="http://achjiang.com/share-know.png" alt="">
            </div>
            <div class="payinfo-list-container">
                <ul class="payinfo-ul">
                    {% for payinfo in payinfos %}
                        <li>
                            <a href="{% url 'payinfo:payinfo_order' %}?payinfo_id={{ payinfo.pk }}">
                                <div class="category-group document-group"></div>
                                <div class="payinfo-info-group">
                                    <p class="payinfo-title">{{ payinfo.title }}</p>
                                    <p class="payinfo-desc">{{ payinfo.profile }}</p>
                                    <p class="price-text">￥{{ payinfo.price }}</p>
                                </div>
                            </a>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <div class="sidebar-container">
            {% include 'base/side.html' %}
        </div>
    </div>
{% endblock %}