apps/news/urls.py
from django.urls import path
from . import views
# from django.shortcuts import reverse


# 设置空间名
app_name = 'news'
urlpatterns = [
	path('', views.index, name='index'),
	path('detail/<news_id>/', views.news_detail, name='news_detail'),
	path('search/', views.search, name='search'),
	path('list/', views.news_list, name='news_list'),
	path('add_comment/', views.add_comment, name='add_comment'),
]

django_01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # 用来拼接一些静态文件路径
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # django自带的admin用户路由界面
    path('', include('apps.news.urls')),  # 新闻路由界面，apps.name用于区分命名空间下对应的urls
    path('account/', include('apps.xfzauth.urls')),  # 登录注册界面的主urls
    path('course/', include('apps.course.urls')),  # 创业课堂页面的主urls
    path('payinfo/', include('apps.payinfo.urls')),  # 支付界面urls
    path('cms/', include('apps.cms.urls')),  # 后台管理系统urls
    path("ueditor/", include("apps.ueditor.urls")),  # 文本编辑器urls
    # 1 将static写在urlpatterns里的写法：
    # static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)[0],
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 2 static写在外面的写法

# 说明;1.告诉当访问media文件时，可以到后面定义的settings.MEDIA_EOOT目录下寻找。这样就可以直接用浏览器通过对应的文件路径访问文件。如果不做这个配置，浏览器是不能直接根据路径访问文件的
# 2.因为urlpatterns是一个列表参数，static()返回值也是一个列表，使用“+”直接变成列表相加，最终的static()也是urlpatterns中的一个元素。等效于：urlpatterns
# += static()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/",include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

apps/news/models.py
from django.db import models


class NewCategory(models.Model):
    """新闻分类表"""
    name = models.CharField(max_length=100)


# aware time：清醒的时间（清醒的知道自己这个时间代表的是哪个时区的）
# navie time：幼稚的时间（不知道自己的时间代表的是哪个时区）


class News(models.Model):
    """新闻表"""
    title = models.CharField(max_length=200)  # 题目
    desc = models.CharField(max_length=200)  # 描述
    thumbnail = models.URLField()  # 缩略图链接
    content = models.TextField()  # 发布内容
    pub_time = models.DateTimeField(auto_now=True)  # 发布时间，设置为当前时间
    # 关联外键
    category = models.ForeignKey(
        "NewCategory",
        on_delete=models.SET_NULL,
        null=True)
    # 默认情况下，category不能为空，null默认是为false，如果我们设置它为空，就需要将null配置成True（允许为空）
    author = models.ForeignKey(
        "xfzauth.User",
        on_delete=models.SET_NULL,
        null=True)

    class Meta:
        # 以后News.objects提出数据的时候，就会按照列表指定的字段排序
        # 如果不加负号，就会默认按照从小到大正序排序
        # 如果加负号，就会按照从大到小倒序排序
        ordering = ['-pub_time']


class Comment(models.Model):
    """评论内容"""
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey(
        "News",
        on_delete=models.CASCADE,
        related_name='comments')
    # 定义一个related——name(别名)
    author = models.ForeignKey("xfzauth.User", on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    """轮播图"""
    image_url = models.URLField()  # 定义一个图片链接的属性
    priority = models.IntegerField(default=0)  # 创建一个优先级属性
    link_to = models.URLField()  # 图片a标签的超链接属性
    pub_time = models.DateTimeField(
        auto_now_add=True)  # 定义一个发布事件，设置事件自动设置为当前时间

    class Meta:
        ordering = ['-priority']

apps/news/forms.py
from django import forms
from apps.forms import FormMixin


class AddCommentForm(forms.Form, FormMixin):
    # 在表单中，CharField和TextField唯一的区别
    # 就是在表单渲染成模板的时候会有区别。
    # CharField会被渲染成Input标签
    # TextField会被渲染成Textarea
    content = forms.CharField()
    news_id = forms.IntegerField()

apps/news/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST, require_GET
from django.conf import settings
from django.http import Http404
# 当我们在查询的条件中需要组合条件时(例如两个条件“且”或者“或”)时。
# 我们可以使用Q()查询对象
from django.db.models import Q
from silk.profiling.profiler import silk_profile

# login_required：只能针对传统的页面跳转（如果没有登录，就跳转到login_url指定的页面）
# 但是他不能处理这种ajax请求。就是说如果通过ajax请求去访问一个需要授权的页面
# 那么这个装饰器的页面跳转功能就不行了,针对Ajax请求的页面跳转自定义一个装饰器
# from django.contrib.auth.decorators import login_required
from apps.xfzauth.decorators import xfz_login_required   # y导入自定义的用于ajax请求的装饰器
from .serializers import NewsSerializer, CommentSerializer  # 导入定义序列化
from utils import restful
from .forms import AddCommentForm
from .models import Comment
from .models import NewCategory, News, Banner


@silk_profile(name='get_news')
def index(request):
    """新闻显示页,加入轮播图"""
    # newses = News.objects.all()
    # 用于加载界面显示新闻的个数，settings中设置的ONE_PAGE_NEWS_COUNT是1，
    # 这里配置后，界面只会展示1篇文章
    newses = News.objects.select_related('category', 'author')[
        0:settings.ONE_PAGE_NEWS_COUNT]
    categories = NewCategory.objects.all()
    banners = Banner.objects.all()  # 获取轮播图
    # context 中''中的数据是传入HTML模板中的变量，
    # print(type(banners), 'banners:%s' % banners)
    context = {
        'newses': newses,
        'categories': categories,
        'banners': banners  # 将轮播图数据返回给前端
    }
    return render(request, 'news/index.html', context=context)


@require_GET
def news_list(request):
    """
    新闻列表,用于当加载更多时，翻页
    """
    # /news/list/?p=3
    # 对于没有捕获的p参数，我们后面加一个默认参数，避免浏览器获取数据类型错误
    page = int(request.GET.get('p', 1))
    # 分类的id就叫做"category_id"
    category_id = int(request.GET.get('category_id', 0))  # 获取分类id
    # offer,limit
    start = settings.ONE_PAGE_NEWS_COUNT * (page - 1)
    end = start + settings.ONE_PAGE_NEWS_COUNT
    # newses：QuerySet -> [News(),News()] 下面的值
    # newses对象： [{"title":"","content":''},{"title":"","content":''}]
    # newses = list(News.objects.all()[start:end].values())
    # value:将QuerySet中的模型对象（比如News()对象）转换为字典
    # 加list直接强制将QuerySet转换为列表

    # 当定义好Newserializers并引入后，就可以直接使用***serializer定义
    if category_id == 0:
        # 如果category_id等于0，说明用户未创建分类
        newses = News.objects.all()[start:end]
    else:
        newses = News.objects.filter(category_id=category_id)[start: end]
    serializer = NewsSerializer(newses, many=True)
    return restful.result(data=serializer.data)


def news_detail(request, news_id):
    """新闻详情 """
    try:
        news = News.objects.select_related(
            'category', 'author').get(
            pk=news_id)
        context = {
            'news': news
        }
        return render(request, 'news/news_detail.html', context=context)
    except News.DoesNotExist:
        raise Http404  # 抛出一个404错误，当抛出404时，django就会在根文件中的templates文件调用一个叫做404的文件


@require_POST
@xfz_login_required
def add_comment(request):
    """评论"""
    # 对于django种如果没有登录用户，也还是会有一个request.user ->AnonymousUser的一个假用户，
    # 这个用户数据是不能存储在数据库的
    form = AddCommentForm(request.POST)
    if form.is_valid():
        content = form.cleaned_data.get('content')
        news_id = form.cleaned_data.get('news_id')
        news = News.objects.get(pk=news_id)
        comment = Comment.objects.create(
            content=content, news=news, author=request.user)  # 创建评论
        serizlize = CommentSerializer(comment)
        return restful.result(data=serizlize.data)  # 获取数据
    else:
        return restful.params_error(message=form.get_error())


def search(request):
    """查询，返回一个查询页面 """
    q = request.GET.get('q')

    # 限制字符串长度超过20
    if len(str(q)) < 20:
        if q:
            # 搜索对象为：title或者content中包含的关键字，有就返回
            newes = News.objects.filter(
                Q(title__icontains=q) | Q(content__icontains=q))
            if newes:
                flag = 2
            else:
                page = int(request.GET.get('p', 1))
                start = settings.ONE_PAGE_NEWS_COUNT * (page - 1)
                end = start + settings.ONE_PAGE_NEWS_COUNT
                newes = News.objects.all()[start:end]
                flag = 1
        else:
            page = int(request.GET.get('p', 1))
            start = settings.ONE_PAGE_NEWS_COUNT * (page - 1)
            end = start + settings.ONE_PAGE_NEWS_COUNT
            newes = News.objects.all()[start:end]
            flag = 0

        context = {'newes': newes, 'flag': flag}
        return render(request, 'news/search.html', context=context)
    else:
        flag = 3
        context = {'flag': flag}
        return render(request, 'news/search.html', context=context)

templates/news/index.html
{# 继承基类 #}
{%  extends 'base/front_base.html' %}
{% load news_filters %}
{# 加载时间过滤器，用于页面时间的显示样式 #}
{% block title %}
    achjiang网站首页
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/news.css' %}">
    {# 轮播图功能代码需要引入的bootstrap.min.js和bootstrap.min.css #}
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base/side.css' %}">
{#  引入arttemplat  #}
    <script src="{% static 'js/template-web.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <script id="news-item" type="text/html">
    {# 该标签是django标签，用于指示包裹的文件不处理，只作为字符串 #}
        {% verbatim %}
        {{ each newses news index }}
            <li>
                <div class="thumbnail-group">
                    <a href="/detail/{{ news.id }}">
                        <img src="{{ news.thumbnail }}" alt="">
                    </a>
                </div>
                <div class="news-group">
                    <div class="title">
                        <a href="/detail/{{ news.id }}">{{ news.title }}</a>
                    </div>
                    <p class="desc">{{ news.desc }}</p>
                    <div class="news-more-group">
                        <span class="category">{{ news.category.name }}</span>
                        <span class="pub-time">{{ news.pub_time|timeSince }}</span>
                        <span class="author">{{ news.author.username }}</span>

                    </div>
                </div>
            </li>
        {{ /each }}
        {% endverbatim %}
    </script>

{% endblock %}

{% block main %}
       <div class="main">
        <div class="main-container">
            <div id="carousel-example-generic" class="carousel slide banner" data-ride="carousel">
  <!-- Indicators 表示的是下面的小点点，轮播图下面的小点点必须和轮播图的数量保持一致 -->
              <ol class="carousel-indicators">
              {# 遍历轮播图 #}
                  {% for banner in banners %}
                      {# 判断轮播图下标是否是0，如果是0，只显示一个，否则，显示多个 #}
                      {% if forloop.counter0 == 0 %}
                          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                      {% else %}
                          <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                      {% endif %}
                  {% endfor %}
{# 删除以前写死的代码 #}
{#                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>#}
{#                <li data-target="#carousel-example-generic" data-slide-to="1"></li>#}

              </ol>

              <!-- 轮播图 -->
              <div class="carousel-inner" role="listbox">
              {# 遍历轮播图 #}
                  {% for banner in banners %}
                      {# 判断遍历的轮播图个数，如果序号为1，则只显示一个，否则，按照遍历的序号显示 #}
                      {% if forloop.counter0 == 0%}
                          <div class="item active">
                       {% else %}
                          <div class="item">
                      {% endif %}
                      {# 加入target属性就可以使得点击a标签时，在一个新的页面打开a标签 #}
                        <a href="{{ banner.link_to }}" target="_blank">
                            <img src="{{ banner.image_url }}" alt="...">
                        </a>
                  </div>
                  {% endfor %}
{# 写死的代码删除掉 #}
{#                <div class="item active">#}
{#                  <img src="https://static-image.xfz.cn/1528792421_261.jpg" alt="...">#}
{#                </div>#}
{#                <div class="item">#}
{#                  <img src="https://static-image.xfz.cn/1528448527_528.jpg" alt="...">#}
              </div>

              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>

            {# news主体部分 #}
            <div class="list-outer-group">
                <ul class="list-tab-group">
{#  class="active" 是默认选中状态   #}
                    <li class="active" data-category-id="0"><a href="javascript:void (0);">最新文章</a></li>
                    {% for category in categories  %}
                        <li data-category-id="{{ category.pk }}"><a href="javascript:void (0);">{{ category.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
            <ul class="news-list-group">
                {% for news in newses %}
                    <li>
                     <div class="thumbnail-group">
                         <a href="{% url 'news:news_detail' news_id=news.pk %}">
                             <img src="{{ news.thumbnail }}" alt="">
                         </a>
                     </div>
                    <div class="news-group">
                        <div class="title">
                            <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                        </div>
                        <p class="desc">{{ news.desc }}</p>
                        <div class="news-more-group">
                            <span class="category">{{ news.category.name }}</span>
                            <span class="pub-time">{{ news.pub_time | time_since}}</span>
                            {# 加入time_since这样在调用时，将pub_time传给time_since #}
                            <span class="author">{{ news.author.username }}</span>

                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="load-more-group">
                <button class="load-more-btn" data-page="2">
                    加载更多
                </button>
            </div>
        </div>
        <div class="sidebar-container">
            {% include 'base/side.html' %}
        </div>
    </div>
{% endblock %}

templates/news/news_detail.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/news_detail.css' %}">
    <meta name="referrer" content="no-referrer" />
    <script src="{% static 'js/template-web.js' %}"></script>
    <script src="{% static 'js/news_detail.js' %}"></script>
    <script id="comment-item" type="text/html">
    {#  在评论处写下模板  #}
    {% verbatim %}
        <li>
            <div class="top-info-group">
                <div class="user-info-group">
                    <img src="http://7xl0ey.com2.z0.glb.qiniucdn.com/1458392835_51884.jpg" alt="">
                    <span class="username-group">{{ comment.author.username }}</span>
                </div>
                <p class="time-group">{{ comment.pub_time|timeSince }}</p>
            </div>
            <p class="comment-content-group">{{ comment.content }}</p>
        </li>
    {% endverbatim %}
</script>


{% endblock %}

{% block main %}
    <div class="main">
        <div class="main-container">
            <div class="article-group">
                    <p class="article-title-group">{{ news.title }}</p>
                    <div class="article-info-group">
                        <div class="left-info-group">
                            <span class="author-time-group">{{ news.author.username }}</span>
                            <span class="author-time-group">{{ news.pub_time|time_since }}</span>
                            <span class="category-group">{{ news.category.name }}</span>
                        </div>
                    </div>
                        <article class="article-content-group">{{ news.content|safe }}</article>
{#  {{ news.content|safe }}中的safe标签就是告诉浏览器content中的html标签是安全的，可以直接解析  #}
                    <div class="comment-group">
                        <h2 class="comment-title">文章评论(0)</h2>
                        {% if user.is_authenticated %}
{#  判断用户是否授权，授权就可以执行下面部分  #}
                            <textarea id="comment-textarea" placeholder="请填写评论" cols="30" rows="10" class="comment-textarea logined-textarea"></textarea>
                        {% else %}
                            <textarea readonly placeholder="立即登录，参与评论~" cols="30" rows="10" class="comment-textarea nologin-textarea"></textarea>
                        {% endif %}
                        <div class="submit-comment-group">
                            <button class="submit-comment-btn" id="submit-comment-btn" data-news-id="{{ news.id }}">评论</button>
                        </div>
                    </div>
                    <ul class="comment-list-group">
                        {#  可以通过news.comments.all拿到所有的评论  #}
                        {% for comment in news.comments.all %}
                            <li>
                            <div class="top-info-group">
                                <div class="user-info-group">
                                    <img src="http://7xl0ey.com2.z0.glb.qiniucdn.com/1458392835_51884.jpg" alt="">
                                    <span class="username-group">{{ comment.author.username }}</span>
                                </div>
                                <p class="time-group">{{ comment.pub_time|time_since }}</p>
                            </div>
                            <p class="comment-content-group">{{ comment.content }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
        </div>
        <div class="sidebar-container">
            {% include 'base/side.html' %}
        </div>
    </div>
{% endblock %}

templates/news/search.html
{% extends 'base/front_base.html' %}
{% load news_filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/search.css' %}">
    <style>
        .search_highlight{
            color: red;
        }
    </style>

    <link rel="stylesheet" href="{% static 'css/news/news.css' %}">
    {# 轮播图功能代码需要引入的bootstrap.min.js和bootstrap.min.css #}
    <link rel="stylesheet" href="{% static 'css/base/side.css' %}">
{#  引入arttemplat  #}
    <script src="{% static 'js/template-web.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script id="news-item" type="text/html">
    {# 该标签是django标签，用于指示包裹的文件不处理，只作为字符串 #}
        {% verbatim %}
        {{ each newes news index }}
            <li>
                <div class="thumbnail-group">
                    <a href="/detail/{{ news.id }}">
                        <img src="{{ news.thumbnail }}" alt="">
                    </a>
                </div>
                <div class="news-group">
                    <div class="title">
                        <a href="/detail/{{ news.id }}">{{ news.title }}</a>
                    </div>
                    <p class="desc">{{ news.desc }}</p>
                    <div class="news-more-group">
                        <span class="category">{{ news.category.name }}</span>
                        <span class="pub-time">{{ news.pub_time|timeSince }}</span>
                        <span class="author">{{ news.author.username }}</span>

                    </div>
                </div>
            </li>
        {{ /each }}
        {% endverbatim %}
    </script>
{% endblock %}

{% block main %}
    <div class="main">
		<div class="main-container">
			<div class="search-group">
                <form action="" method="get">
                    <input type="text" class="search-input" placeholder="请输入关键字" name="q">
                    <button class="search-btn">搜索</button>
                </form>
			</div>
            <div class="list-group">
                {% if flag == 2 %}
                    <p class="list-search-title">
                    搜索结果:
                    </p>
                {% elif flage == 0 %}
{#                    <div class="news-list-group" >#}
                        <p class="list-search-title">请输入搜索内容</p>
{#                    </div>#}
                {% elif flage == 3 %}
{#                    <div class="news-list-group" >#}
                        <p class="list-search-title">查询限制在20个字符以内</p>
{#                    </div>#}
                {% elif flag == 1 %}
                    <div class="news-list-group">
                        <p class="list-search-title" style="color: red;">
                    暂未搜索到相关内容，到<a href="{% url 'news:index' %}">主页</a>在看看？
                    </p>
                    </div>

                {% endif %}
                 <ul class="news-list-group">
                {% for news in newes %}
                    <li>
                     <div class="thumbnail-group">
                         <a href="{% url 'news:news_detail' news_id=news.pk %}">
                             <img src="{{ news.thumbnail }}" alt="">
                         </a>
                     </div>
                    <div class="news-group">
                        <div class="title">
                            <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                        </div>
                        <p class="desc">{{ news.desc }}</p>
                        <div class="news-more-group">
                            <span class="category">{{ news.category.name }}</span>
                            <span class="pub-time">{{ news.pub_time | time_since}}</span>
                            {# 加入time_since这样在调用时，将pub_time传给time_since #}
                            <span class="author">{{ news.author.username }}</span>

                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
                 <div class="load-more-group">
                <button class="load-more-btn" data-page="2">
                    加载更多
                </button>
            </div>
            </div>
		</div>
		<div class="sidebar-container">
            {% include 'base/side.html' %}
        </div>
	</div>
{% endblock %}