apps/cms/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from . import course_views
from . import staff_views

# from rest_framework import routers


app_name = 'cms'

# router = routers.DefaultRouter()
# router.register(path('',))

urlpatterns = [
    path('', views.index, name='index'),
    path('news_list/', views.NewsList.as_view(), name='news_list'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsViem.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.NewsCategoryViem.as_view(), name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners, name='banners'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),

    path('news_show', views.NewsClickShowView.as_view(), name='news_show'),
]
# 课程相关的url
urlpatterns += [
    path('pub_course/', course_views.PubCourse.as_view(), name='pub_course'),
    path('course_category/', course_views.CourseCategoryViem.as_view(), name='course_category'),
    path('add_course_category/', course_views.add_course_category, name='add_course_category'),
    path('edit_course_category/', course_views.edit_course_category, name='edit_course_category'),
    path('delete_course_category/', course_views.delete_course_category, name='delete_course_category'),
    path('course_teacher/', course_views.CourseTeacher.as_view(), name='course_teacher'),
    path('course_teacher/<pk>/', course_views.CourseTeacherDetail.as_view(), name='course_teacher_detail'),
    path('course_teacher_list/', course_views.CourseTeacherList.as_view(), name='course_teacher_list'),
    path('course_teacher_list/<pk>/', course_views.CourseTeacherListDetail.as_view(), name='course_teacher_list_detail'),
]

# 分享资料url
urlpatterns += [
    path('pay_info/', views.PayInfoIndex.as_view(), name='pay_info'),
    path('payinfo_list/', views.PayInfoList.as_view(), name='payinfo_list'),
    path('payinfo/', views.PayInfo.as_view(), name="payinfo"),
    path('payinfo/<pk>/', views.PayInfo.as_view(), name="payinfo_detail"),
]

# 用户管理相关url配置
urlpatterns += [
    path('staffs/', staff_views.staffs, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff'),
    path('user_center/', views.UserCenter.as_view(), name='user_center'),
    path('edit_user_center/', views.EditUserCenter.as_view(), name='edit_user_center'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

apps/news/urls.py
from django.urls import path
from . import views
# from django.shortcuts import reverse


# 设置空间名
app_name = 'news'
urlpatterns = [
	path('', views.index, name='index'),
	path('detail/<news_id>/', views.news_detail, name='news_detail'),
	path('search/', views.search, name='search'),
	path('list/', views.news_list, name='news_list'),
	path('add_comment/', views.add_comment, name='add_comment'),
]

apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('payinfo_order', views.payinfo_order, name='payinfo_order'),
    path('notify_view/', views.notify_view, name='notify_view'),
    path('download_payinfo/', views.download_payinfo, name='download_payinfo'),
    path('order_key/', views.order_key, name='order_key')
]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'
urlpatterns = [
	# path("login/",views.login_view,name='login'), # 第1种写法的url
	path("login/", views.LoginView.as_view(), name='login'),  # 第2种写法的url .as_view()函数是将类转变成函数才能使用
	path("register/", views.RegisterView.as_view(), name='register'),
	path("img_captcha/", views.img_captcha, name='img_captcha'),
	path("sms_captcha/", views.sms_captcha, name='sms_captcha'),
	path("logout/", views.logout_view, name='logout'),
]

django_01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # 用来拼接一些静态文件路径
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # django自带的admin用户路由界面
    path('', include('apps.news.urls')),  # 新闻路由界面，apps.name用于区分命名空间下对应的urls
    path('account/', include('apps.xfzauth.urls')),  # 登录注册界面的主urls
    path('course/', include('apps.course.urls')),  # 创业课堂页面的主urls
    path('payinfo/', include('apps.payinfo.urls')),  # 支付界面urls
    path('cms/', include('apps.cms.urls')),  # 后台管理系统urls
    path("ueditor/", include("apps.ueditor.urls")),  # 文本编辑器urls
    # 1 将static写在urlpatterns里的写法：
    # static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)[0],
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 2 static写在外面的写法

# 说明;1.告诉当访问media文件时，可以到后面定义的settings.MEDIA_EOOT目录下寻找。这样就可以直接用浏览器通过对应的文件路径访问文件。如果不做这个配置，浏览器是不能直接根据路径访问文件的
# 2.因为urlpatterns是一个列表参数，static()返回值也是一个列表，使用“+”直接变成列表相加，最终的static()也是urlpatterns中的一个元素。等效于：urlpatterns
# += static()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/",include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

apps/cms/models.py
from django.db import models

apps/news/models.py
from django.db import models


class NewCategory(models.Model):
    """新闻分类表"""
    name = models.CharField(max_length=100)


# aware time：清醒的时间（清醒的知道自己这个时间代表的是哪个时区的）
# navie time：幼稚的时间（不知道自己的时间代表的是哪个时区）


class News(models.Model):
    """新闻表"""
    title = models.CharField(max_length=200)  # 题目
    desc = models.CharField(max_length=200)  # 描述
    thumbnail = models.URLField()  # 缩略图链接
    content = models.TextField()  # 发布内容
    pub_time = models.DateTimeField(auto_now=True)  # 发布时间，设置为当前时间
    # 关联外键
    category = models.ForeignKey(
        "NewCategory",
        on_delete=models.SET_NULL,
        null=True)
    # 默认情况下，category不能为空，null默认是为false，如果我们设置它为空，就需要将null配置成True（允许为空）
    author = models.ForeignKey(
        "xfzauth.User",
        on_delete=models.SET_NULL,
        null=True)

    class Meta:
        # 以后News.objects提出数据的时候，就会按照列表指定的字段排序
        # 如果不加负号，就会默认按照从小到大正序排序
        # 如果加负号，就会按照从大到小倒序排序
        ordering = ['-pub_time']


class Comment(models.Model):
    """评论内容"""
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey(
        "News",
        on_delete=models.CASCADE,
        related_name='comments')
    # 定义一个related——name(别名)
    author = models.ForeignKey("xfzauth.User", on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    """轮播图"""
    image_url = models.URLField()  # 定义一个图片链接的属性
    priority = models.IntegerField(default=0)  # 创建一个优先级属性
    link_to = models.URLField()  # 图片a标签的超链接属性
    pub_time = models.DateTimeField(
        auto_now_add=True)  # 定义一个发布事件，设置事件自动设置为当前时间

    class Meta:
        ordering = ['-priority']

apps/cms/views.py
# coding=utf-8
import os
from datetime import datetime  # 获取时间参数模块
from urllib import parse  # 导入url函数
import logging

import qiniu
from django.shortcuts import render, redirect, reverse
from django.contrib.admin.views.decorators import staff_member_required
# 导入django自带的确定是否登陆和是否是工作人员的装饰器，后面可以跟重定向的url
from django.views.generic import View  # 使用类定义函数时，变量需要引入该模块
# 限制函数，只能使用post的请求，才能访问某个函数
from django.views.decorators.http import require_POST, require_GET
# 导入对应的forms表单，用于与数据库表单数据关联
from django.conf import settings
from django.contrib.auth.decorators import login_required  # 导入登录验证函数
from django.utils.decorators import method_decorator  # 验证登录才能访问函数的装饰器
from django.core.paginator import Paginator  # django自带分页处理
# 可以在该模块后给出一个条件，这样就可以要求对应的权限
from django.contrib.auth.decorators import permission_required

from apps.news.models import NewCategory, News, Banner   # 导入对应的数据库表单
from apps.payinfo.models import Payinfo
from utils import restful  # 引入自定义的浏览器返回的错误信息文件
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditBannerForm, EditNewsForm, EditUserCenterForm
from apps.xfzauth.decorators import xfz_permission_required
from apps.xfzauth.models import User
# from apps.course.models import Teacher


logger = logging.getLogger('django')  # 'django'与配置文件中的logger名称一致
# 调用staff_member_required函数来验证staff处的值是否为True，
# 不为真就跳转到login_url='...'对应的链接。如果为真则执行后面的函数


@staff_member_required(login_url='/account/login/')
def index(request):
    """# 1.cms主界面"""
    return render(request, 'cms/index.html')


@method_decorator([xfz_permission_required(News)], name='dispatch')
class NewsList(View):
    """
    新闻列表
    # method_decorator是一个将装饰器函数转换为装饰器方法的，参数1：装饰器，参数2：
    """

    def get(self, request):
        page = int(request.GET.get('p', 1))  # 获取当前所在页数
        start = request.GET.get('start')   # 通过前端的标签名获取值
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0))

        # newses = News.objects.select_related ('category', 'author').all () #
        # 获取所有新闻分类及作者
        newses = News.objects.select_related('category', 'author')

        # 过滤出指定时间内的新闻
        if start and end:
            start_date = datetime.strptime(start, '%Y/%m/%d')
            end_date = datetime.strptime(end, '%Y/%m/%d')
            newses = newses.filter(pub_time__range=(start_date, end_date))

        # 过滤标题中包含指定关键字的新闻
        if title:
            newses = newses.filter(
                title__icontains=title)  # i指忽略大小写，contains指包含

        # 过滤对应分类的新闻
        if category_id != 0:
            newses = newses.filter(category=category_id)
            # print('分类名称：%s' % category_id, '新闻数量%s' % len(newses))
        paginator = Paginator(newses, 2)  # 将获取的新闻内容按照每页2篇的形式进行分页
        page_obj = paginator.page(page)  # 获取对应分页的数据
        categories = NewCategory.objects.all()

        # 通过分页函数返回分页数据，获取每一页的数据
        pagination_data = self.get_pagination_data(paginator, page_obj)
        '''查询内容组成的查询url是否应该带'''
        # 方法1：
        # if (start and end) or title or category_id!=0 :
        # 	url_query = '&' + parse.urlencode ({
        # 		'start': start,
        # 		'end': end,
        # 		'title': title,
        # 		'category': category_id
        # 	})
        # else:
        # 	url_query = ''
        # 方法2：
        if start or end or title or category_id:
            url_query = '&' + parse.urlencode({
                'start': start,
                'end': end,
                'title': title,
                'category': category_id
            })
        else:
            url_query = ''

        context = {
            'categories': categories,
            'paginator': paginator,
            'page_obj': page_obj,
            'newses': page_obj.object_list,  # 获取该页数据的内容
            'title': title,
            'start': start,
            'end': end,
            'category_id': category_id,
            # 查询内容url
            'url_query': url_query
        }
        logger.info('用户查询了[%s]' % context['url_query'])
        # print(context['url_query'])  # 打印测试输出的是否是我们查询内容
        context.update(pagination_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=1):
        """
        分页功能
        < 1...5,6,7,8,9...13 >基本模式，即选中页前后留出2页，多出的用...代替。
        当选择最前或最后前后两页包含或者临近第一页或最后一页，那么取消显示...
        """
        current_page = page_obj.number  # 获取当前页码
        num_pages = paginator.num_pages

        # 左侧是否应该显示三个点
        left_has_more = False

        # 右侧是否应该显示三个点
        right_has_more = False

        # 左侧显示页
        # 判断当前页数小于需要展示页数+2时，不显示三个点
        l_start = current_page - around_count  # 左侧的开始页码数
        l_end = current_page  # 右侧结束页码数
        if current_page <= around_count + 2:
            left_pages = range(1, l_end)
        else:
            left_has_more = True
            left_pages = range(l_start, l_end)

        # 右侧显示页
        r_start = current_page + 1
        r_end = current_page + around_count + 1   # ? 说绝对位置是是这个位置+1?
        if current_page >= num_pages - around_count - 1:
            right_pages = range(r_start, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(r_start, r_end)
        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages,
            'current_page': current_page
        }


@method_decorator([login_required(login_url='/account/login/'),
                   xfz_permission_required(News)], name='dispatch')
class WriteNewsView(View):
    """编辑页面"""

    def get(self, request):
        context = {
            'categories': NewCategory.objects.all()
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            # cleaned_data：这个属性，必须要调用is_valid后，
            # 如果验证通过了才会生成这个属性，否则没有这个属性
            # 获取表单中的各个数据
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            # 获取分类id,因为是通过外键获取的id,
            # 需要通过NewCategory来获取实际分类名称
            category = NewCategory.objects.get(pk=category_id)  # 获取分类名
            News.objects.create(
                title=title,
                desc=desc,
                thumbnail=thumbnail,
                content=content,
                category=category,
                author=request.user)
            return restful.ok() and redirect(reverse('cms:news_list'))
        else:
            return restful.params_error(message=form.get_error())


@method_decorator([login_required(login_url='/account/login/'),
                   xfz_permission_required(News)], name='dispatch')
class EditNewsViem(View):
    """
    编辑新闻
    # dispatch函数解释,当把装饰器命名未dispatch方法时，它就会对请求进行判断，
    # 如果时get请求，就调用get函数；如果请求时post请求时，
    就调用post请求。这样装饰器就可以把两种请求都涉及到
    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            return self.get(request)
        elif request.method == 'POST':
            return self.post(request)
    """

    def get(self, request):
        pk = request.GET.get('pk')
        news = News.objects.get(pk=pk)
        categories = NewCategory.objects.all()
        context = {
            'news': news,
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            pk = form.cleaned_data.get('pk')
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            category_id = form.cleaned_data.get('category')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category = NewCategory.objects.get(pk=category_id)
            News.objects.filter(
                pk=pk).update(
                title=title,
                desc=desc,
                thumbnail=thumbnail,
                content=content,
                category=category)
            logger.info('编辑新闻%s成功！' % title)
            return restful.ok()
        else:
            logger.error('编辑新闻失败！')
            return restful.params_error(form.get_error())


@xfz_permission_required(News)
def delete_news(request):
    """删除新闻"""
    pk = request.POST.get('pk')
    news = News.objects.filter(pk=pk)
    news.delete()
    logger.warning('删除新闻%s!' % news.values('title'))
    return restful.ok()


@method_decorator([login_required(login_url='/account/login/'),
                   xfz_permission_required(NewCategory)], name='dispatch')
# @xfz_permission_required(NewCategory)
# 对于使用class定义的函数，装饰器的使用需要注意，不能使用这种方式，这种只适合def直接定义的函数
class NewsCategoryViem(View):
    """
    新闻分类函数
    :return
    """

    def get(self, request):
        # categories是指所有的类别,使用id进行排序
        categories = NewCategory.objects.order_by(
            '-id')  # 获得所有的分类集合，排序按照'-id'的顺序
        '''使用select_related方法获取对象，在对该对象进行处理时，不用经过数据库查询了，减少了查询次数'''
        newses = News.objects.select_related('category')  # 从新闻表中按照分类筛选出一个集合
        category_nums = {}  # 定义一个空字典，用于后面存放，分类及对应的分类数量

        # 通过一个循环得到分类名及对应分类新闻的数量，并将两者以键值对的形式存在字典category_nums中
        for category in categories:
            # 获取各分类数量
            # 方法1：使用len()方法获取长度：
            # 通过分类名对newses数据进行过滤，用len()获取该分类新闻的数量
            nums = len(newses.filter(category__name=category.name))
            # 方法2：使用count()方法统计数量：
            # nums = newses.filter(category__name=category.name).count()
            # 将筛选得到的每一个分类及分类数量以键值对的形式存在字典中

templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 后台管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}"/>
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'sweetalert/xfzalert.js' %}"></script>
    <script src="{% static 'js/xfzajax.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/cms_base.js' %}"></script>
{% block head %}{% endblock %}

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="{% url 'cms:index' %}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">后台管理</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1531164611306&di=0359af64fee74589cf8d34fcb8db45ec&imgtype=0&src=http%3A%2F%2Fmvimg1.meitudata.com%2F54e56071c7a8b7322.jpg" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1531164611306&di=0359af64fee74589cf8d34fcb8db45ec&imgtype=0&src=http%3A%2F%2Fmvimg1.meitudata.com%2F54e56071c7a8b7322.jpg" class="img-circle" alt="User Image">

                                <p>
                                    {{ user.username }}
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'cms:user_center' %}" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'xfzauth:logout' %}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <aside class="main-sidebar">
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="搜索...">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <ul class="sidebar-menu" data-widget="tree">
                <li>
                    <a href="{% url 'news:index' %}">
                        <i class="fa fa-mail-reply-all"></i>
                        <span>返回网站首页</span>
                    </a>
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>cms首页</span>
                    </a>
                </li>
                {# 根据用户权限显示对应的页面 #}
                {% if perms.news.change_news %}
                    <li class="header">文章管理</li>
                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list">
                                <span>文章列表</span>
                            </i>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布文章</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>文章分类</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:banners' %}">
                            <i class="fa fa-picture-o">
                                <span>轮播图管理</span>
                            </i>
                        </a>
                    </li>
                {% endif %}
                {% if perms.course.change_course %}
                    <li class="header">课程资讯管理</li>
                    <li><a href="{% url 'cms:pub_course' %}">
                    <i class="fa fa-tv">
                        <span>发布课程资讯</span>
                    </i>
                </a></li>
                    <li>
                        <a href="{% url 'cms:course_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>课程资讯分类</span>
                        </a>
                    </li>

                {% endif %}
                {% if user.is_superuser %}
                    <li class="header">人员管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>用户管理</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:course_teacher' %}">
                            <i class="fa fa-cog"></i>
                            <span>教师管理</span>
                        </a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="header">资料管理</li>
                    <li>
                    <a href="{% url 'cms:payinfo_list' %}">
                        <i class="fa fa-folder"></i>
                        <span>资料列表</span>
                    </a>
                    </li>
                    <li>
{#                    <a href="{% url 'cms:pub_payinfo' %}">#}
                    <a href="{% url 'cms:pay_info' %}">
                        <i class="fa fa-leanpub"></i>
                        <span>发布资料</span>
                    </a>
                    </li>
                {% endif %}
            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>

        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>

    <footer class="main-footer">
        CMS后台管理
    </footer>
</div>
</body>
</html>

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block content-header %}
    <h1>博客后台管理首页</h1>
{% endblock %}

templates/cms/staffs.html
{% extends 'cms/base.html' %}

{% block title %}
人员管理
{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
<h1>人员管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <a href="{% url 'cms:add_staff' %}" class="btn btn-primary pull-right">新增人员</a>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>用户名</th>
                        <th>手机号码</th>
                        <th>所属分组</th>
                        <th>人员管理</th>
                    </tr>
                </thead>
                <tbody>
                {% for staff in staffs %}
                    <tr>
                        <td>{{ staff.username }}</td>
                        <td>{{ staff.telephone }}</td>
                        <td>
                            {% if staff.is_superuser %}
                                超级管理员
                            {% else %}
                                {% for group in staff.groups.all %}
                                    {{ group.name }}
                                {% endfor %}
                            {% endif %}
                        </td>
                        <td>
                            <button class="btn btn-info btn-xs">编辑</button>
                            <button class="btn btn-danger btn-xs">删除</button>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="box-footer"></div>
    </div>
</div>
</div>
{% endblock %}